### ISSUE TITLE
Friends example from Tests causing failure

### ISSUE THREAD

**Issue by buddha314** [lab-v2/pyreason#42]
Running within a Jupyter notebook.  The cell below creates the following error.  Note the `.graphml` file is correct.  Also note that the error says `timesteps=1` but that's a cut/paste issue.

```
    # Load all the files into pyreason
    pr.load_graphml(graph_path)
    pr.add_rule(pr.Rule('popular(x) <-1 popular(y), Friends(x,y), owns(y,z), owns(x,z)', 'popular_rule'))
    pr.add_fact(pr.Fact('popular-fact', 'Mary', 'popular', [1, 1], 0, 2))

    # Run the program for two timesteps to see the diffusion take place
    interpretation = pr.reason(timesteps=2)

    # Display the changes in the interpretation for each timestep
    dataframes = pr.filter_and_sort_nodes(interpretation, ['popular'])
    for t, df in enumerate(dataframes):
        print(f'TIMESTEP - {t}')
        print(df)
        print()
```

Leading to

```
{
	"name": "KeyError",
	"message": "",
	"stack": "---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[18], line 10
      7 pr.add_fact(pr.Fact('popular-fact', 'Mary', 'popular', [1, 1], 0, 2))
      9 # Run the program for two timesteps to see the diffusion take place
---> 10 interpretation = pr.reason(timesteps=1)
     12 # Display the changes in the interpretation for each timestep
     13 dataframes = pr.filter_and_sort_nodes(interpretation, ['popular'])

File /usr/local/lib/python3.11/site-packages/pyreason/pyreason.py:542, in reason(timesteps, convergence_threshold, convergence_bound_threshold, again, node_facts, edge_facts)
    540         print(f\"\
Program used {mem_usage-start_mem} MB of memory\")
    541     else:
--> 542         interp = _reason(timesteps, convergence_threshold, convergence_bound_threshold)
    543 else:
    544     if settings.memory_profile:

File /usr/local/lib/python3.11/site-packages/pyreason/pyreason.py:620, in _reason(timesteps, convergence_threshold, convergence_bound_threshold)
    617 __program.specific_edge_labels = __specific_edge_labels
    619 # Run Program and get final interpretation
--> 620 interpretation = __program.reason(timesteps, convergence_threshold, convergence_bound_threshold, settings.verbose)
    622 return interpretation

File /usr/local/lib/python3.11/site-packages/pyreason/scripts/program/program.py:41, in Program.reason(self, tmax, convergence_threshold, convergence_bound_threshold, verbose)
     39 else:
     40 \tself.interp = Interpretation(self._graph, self._ipl, self._annotation_functions, self._reverse_graph, self._atom_trace, self._save_graph_attributes_to_rule_trace, self._canonical, self._inconsistency_check, self._store_interpretation_changes, self._update_mode)
---> 41 self.interp.start_fp(self._tmax, self._facts_node, self._facts_edge, self._rules, verbose, convergence_threshold, convergence_bound_threshold)
     43 return self.interp

File /usr/local/lib/python3.11/site-packages/pyreason/scripts/interpretation/interpretation.py:171, in Interpretation.start_fp(self, tmax, facts_node, facts_edge, rules, verbose, convergence_threshold, convergence_bound_threshold, again)
    169 self._convergence_mode, self._convergence_delta = self._init_convergence(convergence_bound_threshold, convergence_threshold)
    170 max_facts_time = self._init_facts(facts_node, facts_edge, self.facts_to_be_applied_node, self.facts_to_be_applied_edge, self.facts_to_be_applied_node_trace, self.facts_to_be_applied_edge_trace, self.atom_trace)
--> 171 self._start_fp(rules, max_facts_time, verbose, again)

File /usr/local/lib/python3.11/site-packages/pyreason/scripts/interpretation/interpretation.py:196, in Interpretation._start_fp(self, rules, max_facts_time, verbose, again)
    195 def _start_fp(self, rules, max_facts_time, verbose, again):
--> 196 \tfp_cnt, t = self.reason(self.interpretations_node, self.interpretations_edge, self.tmax, self.prev_reasoning_data, rules, self.nodes, self.edges, self.neighbors, self.reverse_neighbors, self.rules_to_be_applied_node, self.rules_to_be_applied_edge, self.edges_to_be_added_node_rule, self.edges_to_be_added_edge_rule, self.rules_to_be_applied_node_trace, self.rules_to_be_applied_edge_trace, self.facts_to_be_applied_node, self.facts_to_be_applied_edge, self.facts_to_be_applied_node_trace, self.facts_to_be_applied_edge_trace, self.ipl, self.rule_trace_node, self.rule_trace_edge, self.rule_trace_node_atoms, self.rule_trace_edge_atoms, self.reverse_graph, self.atom_trace, self.save_graph_attributes_to_rule_trace, self.canonical, self.inconsistency_check, self.store_interpretation_changes, self.update_mode, max_facts_time, self.annotation_functions, self._convergence_mode, self._convergence_delta, verbose, again)
    197 \tself.time = t - 1
    198 \t# If we need to reason again, store the next timestep to start from

File /usr/local/lib/python3.11/site-packages/numba/typed/dictobject.py:778, in impl()
    776 ix, val = _dict_lookup(d, castedkey, hash(castedkey))
    777 if ix == DKIX.EMPTY:
--> 778     raise KeyError()
    779 elif ix < DKIX.EMPTY:
    780     raise AssertionError(\"internal dict error during lookup\")

KeyError: "
}
```

**Comment by dyumanaditya** [comment]
Hi @buddha314

Unfortunately at the moment PyReason does not work properly with Jupyter notebooks, can you try running your code in a single `.py` file and see if you get the same error?

The reason for this is we don't have "pyreason objects" all reasoning is happening directly on top of the library. We are building support for Jupyter notebooks.

**Comment by f-bdolan** [comment]
Same user, different account.

Thanks for the response!! I'm now trying it within a virtualenv on a Windows machine. Here is my new code/error pair.

```
# Re-create the friends graph from the PyR demo to get started
import pyreason as pr
import networkx as nx

# ================================ CREATE GRAPH====================================
# Create a Directed graph
g = nx.DiGraph()

# Add the nodes
g.add_nodes_from(['John', 'Mary', 'Justin'])
g.add_nodes_from(['Dog', 'Cat'])

# Add the edges and their attributes. When an attribute = x which is <= 1, the annotation
# associated with it will be [x,1]. NOTE: These attributes are immutable
# Friend edges
g.add_edge('Justin', 'Mary', Friends=1)
g.add_edge('John', 'Mary', Friends=1)
g.add_edge('John', 'Justin', Friends=1)

# Pet edges
g.add_edge('Mary', 'Cat', owns=1)
g.add_edge('Justin', 'Cat', owns=1)
g.add_edge('Justin', 'Dog', owns=1)
g.add_edge('John', 'Dog', owns=1)


pr.add_rule('popular(x) <-1 popular(y), Friends(x,y), owns(y,z), owns(x,z)', 'popular_rule')

pr.add_fact(pr.Fact(name='popular-fact', component='Mary', attribute='popular', bound=[1, 1], start_time=0, end_time=2))
interpretation = pr.reason(timesteps=2)

```

And the error truncated by the terminal

```
(.env) PS C:\Users\bdolan\src\sparemints\pyreasonin> python .\friends.py
Imported PyReason for the first time. Initializing ... this will take a minute
Traceback (most recent call last):
  File "C:\Users\bdolan\src\sparemints\pyreasonin\friends.py", line 2, in <module>
    import pyreason as pr
  File "C:\Users\bdolan\src\sparemints\pyreasonin\.env\Lib\site-packages\pyreason\__init__.py", line 24, in <module>
    reason(timesteps=2)
  File "C:\Users\bdolan\src\sparemints\pyreasonin\.env\Lib\site-packages\pyreason\pyreason.py", line 542, in reason
    interp = _reason(timesteps, convergence_threshold, convergence_bound_threshold)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bdolan\src\sparemints\pyreasonin\.env\Lib\site-packages\pyreason\pyreason.py", line 620, in _reason
    interpretation = __program.reason(timesteps, convergence_threshold, convergence_bound_threshold, settings.verbose)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bdolan\src\sparemints\pyreasonin\.env\Lib\site-packages\pyreason\scripts\program\program.py", line 41, in reason
    self.interp.start_fp(self._tmax, self._facts_node, self._facts_edge, self._rules, verbose, convergence_threshold, convergence_bound_threshold)
  File "C:\Users\bdolan\src\sparemints\pyreasonin\.env\Lib\site-packages\pyreason\scripts\interpretation\interpretation.py", line 171, in start_fp
    self._start_fp(rules, max_facts_time, verbose, again)
  File "C:\Users\bdolan\src\sparemints\pyreasonin\.env\Lib\site-packages\pyreason\scripts\interpretation\interpretation.py", line 196, in _start_fp
    fp_cnt, t = self.reason(self.interpretations_node, self.interpretations_edge, self.tmax, self.prev_reasoning_data, rules, self.nodes, self.edges, self.neighbors, self.reverse_neighbors, self.rules_to_be_applied_node, self.rules_to_be_applied_edge, self.edges_to_be_added_node_rule, self.edges_to_be_added_edge_rule, self.rules_to_be_applied_node_trace, self.rules_to_be_applied_edge_trace, self.facts_to_be_applied_node, self.facts_to_be_applied_edge, self.facts_to_be_applied_node_trace, self.facts_to_be_applied_edge_trace, self.ipl, self.rule_trace_node, self.rule_trace_edge, self.rule_trace_node_atoms, self.rule_trace_edge_atoms, self.reverse_graph, 
self.atom_trace, self.save_graph_attributes_to_rule_trace, self.canonical, self.inconsistency_check, self.store_interpretation_changes, self.update_mode, max_facts_time, self.annotation_functions, self._convergence_mode, self._convergence_delta, verbose, again)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bdolan\src\sparemints\pyreasonin\.env\Lib\site-packages\numba\core\dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\bdolan\src\sparemints\pyreasonin\.env\Lib\site-packages\numba\core\dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: Handle with contexts)
Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify Tuple(uint16, unicode_type, Label, numba.IntervalType(('l', float64), ('u', float64), ('s', bool), ('prev_l', float64), ('prev_u', float64)), bool, bool) and int64 for 'i.28', defined at C:\Users\bdolan\src\sparemints\pyreasonin\.env\Lib\site-packages\pyreason\scripts\interpretation\interpretation.py (464)

File ".env\Lib\site-packages\pyreason\scripts\interpretation\interpretation.py", line 464:
        def reason(interpretations_node, interpretations_edge, tmax, prev_reasoning_data, rules, nodes, edges, neighbors, reverse_neighbors, rules_to_be_applied_node, rules_to_be_applied_edge, edges_to_be_added_node_rule, edges_to_be_added_edge_rule, rules_to_be_applied_node_trace, rules_to_be_applied_edge_trace, facts_to_be_applied_node, facts_to_be_applied_edge, facts_to_be_applied_node_trace, facts_to_be_applied_edge_trace, ipl, rule_trace_node, rule_trace_edge, rule_trace_node_atoms, rule_trace_edge_atoms, reverse_graph, atom_trace, save_graph_attributes_to_rule_trace, canonical, inconsistency_check, store_interpretation_changes, update_mode, max_facts_time, annotation_functions, convergence_mode, convergence_delta, verbose, again):
     <source elided>
                                # Remove from rules to be applied and edges to be applied lists after coming out from loop
                                rules_to_be_applied_node[:] = numba.typed.List([rules_to_be_applied_node[i] for i in range(len(rules_to_be_applied_node)) if i not in rules_to_remove_idx])
    ^

During: typing of assignment at C:\Users\bdolan\src\sparemints\pyreasonin\.env\Lib\site-packages\pyreason\scripts\interpretation\interpretation.py (464)

File ".env\Lib\site-packages\pyreason\scripts\interpretation\interpretation.py", line 464:
        def reason(interpretations_node, interpretations_edge, tmax, prev_reasoning_data, rules, nodes, edges, neighbors, reverse_neighbors, rules_to_be_applied_node, rules_to_be_applied_edge, edges_to_be_added_node_rule, edges_to_be_added_edge_rule, rules_to_be_applied_node_trace, rules_to_be_applied_edge_trace, facts_to_be_applied_node, facts_to_be_applied_edge, facts_to_be_applied_node_trace, facts_to_be_applied_edge_trace, ipl, rule_trace_node, rule_trace_edge, rule_trace_node_atoms, rule_trace_edge_atoms, reverse_graph, atom_trace, save_graph_attributes_to_rule_trace, canonical, inconsistency_check, store_interpretation_changes, update_mode, max_facts_time, annotation_functions, convergence_mode, convergence_delta, verbose, again):
     <source elided>
                                # Remove from rules to be applied and edges to be applied lists after coming out from loop
                                rules_to_be_applied_node[:] = numba.typed.List([rules_to_be_applied_node[i] for i in range(len(rules_to_be_applied_node)) if i not in rules_to_remove_idx])
    ^
```

**Comment by f-hkobin** [comment]
@f-bdolan Looks like in the first error log posted you're using Python 3.11; it may be worth retrying with python<=3.10 per #25 . I'd suggest retrying with an earlier Python version first and seeing if the issue persists. 
The python version is likely the issue for your second error log - Numba has an issue with newer Python versions.

**Comment by dyumanaditya** [comment]
@buddha314 what @f-hkobin mentioned is correct. Could you try with Python <= 3.10 and let me know if the problem persists?

**Comment by f-bdolan** [comment]
Yes, I tried it and @f-hkobin was correct! Thanks everyone
