### ISSUE TITLE
Uniformative error

### ISSUE THREAD

**Issue by f-bdolan** [lab-v2/pyreason#58]
I'm not sure if this error is pointing me towards the solution or not. I'm attempting to use PyR for simple real-valued logic and am building a case. This script:

```
import networkx as nx
import pyreason as pr

g = nx.DiGraph()
g.add_nodes_from(['A', 'B', 'C'])
g.add_edge('A', 'B', Buddies=0.5)


pr.add_rule(pr.Rule("co_occur(x) <- 1, Buddies(x, y)", 'it_happened'))
interpreter = pr.reason(timesteps=2)
```

Leads to this (uninformative) error.

```
Imported PyReason for the first time. Initializing ... this will take a minute
Traceback (most recent call last):
  File "/Users/bdolan/src/ramen/real-value-logic-pyr/simple_logic.py", line 2, in <module>
    import pyreason as pr
  File "/Users/bdolan/src/ramen/real-value-logic-pyr/.env/lib/python3.12/site-packages/pyreason/__init__.py", line 24, in <module>
    reason(timesteps=2)
  File "/Users/bdolan/src/ramen/real-value-logic-pyr/.env/lib/python3.12/site-packages/pyreason/pyreason.py", line 543, in reason
    interp = _reason(timesteps, convergence_threshold, convergence_bound_threshold)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bdolan/src/ramen/real-value-logic-pyr/.env/lib/python3.12/site-packages/pyreason/pyreason.py", line 621, in _reason
    interpretation = __program.reason(timesteps, convergence_threshold, convergence_bound_threshold, settings.verbose)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bdolan/src/ramen/real-value-logic-pyr/.env/lib/python3.12/site-packages/pyreason/scripts/program/program.py", line 41, in reason
    self.interp.start_fp(self._tmax, self._facts_node, self._facts_edge, self._rules, verbose, convergence_threshold, convergence_bound_threshold)
  File "/Users/bdolan/src/ramen/real-value-logic-pyr/.env/lib/python3.12/site-packages/pyreason/scripts/interpretation/interpretation.py", line 171, in start_fp
    self._start_fp(rules, max_facts_time, verbose, again)
  File "/Users/bdolan/src/ramen/real-value-logic-pyr/.env/lib/python3.12/site-packages/pyreason/scripts/interpretation/interpretation.py", line 196, in _start_fp
    fp_cnt, t = self.reason(self.interpretations_node, self.interpretations_edge, self.tmax, self.prev_reasoning_data, rules, self.nodes, self.edges, self.neighbors, self.reverse_neighbors, self.rules_to_be_applied_node, self.rules_to_be_applied_edge, self.edges_to_be_added_node_rule, self.edges_to_be_added_edge_rule, self.rules_to_be_applied_node_trace, self.rules_to_be_applied_edge_trace, self.facts_to_be_applied_node, self.facts_to_be_applied_edge, self.facts_to_be_applied_node_trace, self.facts_to_be_applied_edge_trace, self.ipl, self.rule_trace_node, self.rule_trace_edge, self.rule_trace_node_atoms, self.rule_trace_edge_atoms, self.reverse_graph, self.atom_trace, self.save_graph_attributes_to_rule_trace, self.canonical, self.inconsistency_check, self.store_interpretation_changes, self.update_mode, max_facts_time, self.annotation_functions, self._convergence_mode, self._convergence_delta, verbose, again)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bdolan/src/ramen/real-value-logic-pyr/.env/lib/python3.12/site-packages/numba/core/dispatcher.py", line 423, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/bdolan/src/ramen/real-value-logic-pyr/.env/lib/python3.12/site-packages/numba/core/dispatcher.py", line 364, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: Handle with contexts)
Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify Tuple(uint16, unicode_type, Label, numba.IntervalType(('l', float64), ('u', float64), ('s', bool), ('prev_l', float64), ('prev_u', float64)), bool, bool) and int64 for 'i.28', defined at /Users/bdolan/src/ramen/real-value-logic-pyr/.env/lib/python3.12/site-packages/pyreason/scripts/interpretation/interpretation.py (464)

File ".env/lib/python3.12/site-packages/pyreason/scripts/interpretation/interpretation.py", line 464:
	def reason(interpretations_node, interpretations_edge, tmax, prev_reasoning_data, rules, nodes, edges, neighbors, reverse_neighbors, rules_to_be_applied_node, rules_to_be_applied_edge, edges_to_be_added_node_rule, edges_to_be_added_edge_rule, rules_to_be_applied_node_trace, rules_to_be_applied_edge_trace, facts_to_be_applied_node, facts_to_be_applied_edge, facts_to_be_applied_node_trace, facts_to_be_applied_edge_trace, ipl, rule_trace_node, rule_trace_edge, rule_trace_node_atoms, rule_trace_edge_atoms, reverse_graph, atom_trace, save_graph_attributes_to_rule_trace, canonical, inconsistency_check, store_interpretation_changes, update_mode, max_facts_time, annotation_functions, convergence_mode, convergence_delta, verbose, again):
     <source elided>
				# Remove from rules to be applied and edges to be applied lists after coming out from loop
				rules_to_be_applied_node[:] = numba.typed.List([rules_to_be_applied_node[i] for i in range(len(rules_to_be_applied_node)) if i not in rules_to_remove_idx])
    ^

During: typing of assignment at /Users/bdolan/src/ramen/real-value-logic-pyr/.env/lib/python3.12/site-packages/pyreason/scripts/interpretation/interpretation.py (464)

File ".env/lib/python3.12/site-packages/pyreason/scripts/interpretation/interpretation.py", line 464:
	def reason(interpretations_node, interpretations_edge, tmax, prev_reasoning_data, rules, nodes, edges, neighbors, reverse_neighbors, rules_to_be_applied_node, rules_to_be_applied_edge, edges_to_be_added_node_rule, edges_to_be_added_edge_rule, rules_to_be_applied_node_trace, rules_to_be_applied_edge_trace, facts_to_be_applied_node, facts_to_be_applied_edge, facts_to_be_applied_node_trace, facts_to_be_applied_edge_trace, ipl, rule_trace_node, rule_trace_edge, rule_trace_node_atoms, rule_trace_edge_atoms, reverse_graph, atom_trace, save_graph_attributes_to_rule_trace, canonical, inconsistency_check, store_interpretation_changes, update_mode, max_facts_time, annotation_functions, convergence_mode, convergence_delta, verbose, again):
     <source elided>
				# Remove from rules to be applied and edges to be applied lists after coming out from loop
				rules_to_be_applied_node[:] = numba.typed.List([rules_to_be_applied_node[i] for i in range(len(rules_to_be_applied_node)) if i not in rules_to_remove_idx])
    ^
```

**Comment by f-bdolan** [comment]
Acting on a tip from @f-hkobin this was due to the use of Python 3.12 (my fault). However, the error is still uninformative and I believe it would be useful to keep this open.

**Comment by dyumanaditya** [comment]
Hi @f-bdolan, Yes this is most likely because of an issue with numba and python 3.12. Since this is on Numba's end we cannot do anything about it. I'm going to close this because we have a section in the readme describing which python versions work (https://github.com/lab-v2/pyreason?tab=readme-ov-file#3-install)
